version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types: ["minor", "patch"]
      prod-minor-patch:
        dependency-type: "production"
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
